export interface SurahMeta {
  id: number;
  name: string;
  transliteration: string;
  translation: string;
  type: "Meccan" | "Medinan";
  ayahs: number;
}

export const SURAH_LIST: SurahMeta[] = [
  { id: 1, name: "الفاتحة", transliteration: "Al-Fatihah", translation: "The Opening", type: "Meccan", ayahs: 7 },
  { id: 2, name: "البقرة", transliteration: "Al-Baqarah", translation: "The Cow", type: "Medinan", ayahs: 286 },
  { id: 3, name: "آل عمران", transliteration: "Ali 'Imran", translation: "Family of Imran", type: "Medinan", ayahs: 200 },
  { id: 4, name: "النساء", transliteration: "An-Nisa", translation: "The Women", type: "Medinan", ayahs: 176 },
  { id: 5, name: "المائدة", transliteration: "Al-Ma'idah", translation: "The Table Spread", type: "Medinan", ayahs: 120 },
  { id: 6, name: "الأنعام", transliteration: "Al-An'am", translation: "The Cattle", type: "Meccan", ayahs: 165 },
  { id: 7, name: "الأعراف", transliteration: "Al-A'raf", translation: "The Heights", type: "Meccan", ayahs: 206 },
  { id: 8, name: "الأنفال", transliteration: "Al-Anfal", translation: "The Spoils of War", type: "Medinan", ayahs: 75 },
  { id: 9, name: "التوبة", transliteration: "At-Tawbah", translation: "The Repentance", type: "Medinan", ayahs: 129 },
  { id: 10, name: "يونس", transliteration: "Yunus", translation: "Jonah", type: "Meccan", ayahs: 109 },
  { id: 11, name: "هود", transliteration: "Hud", translation: "Hud", type: "Meccan", ayahs: 123 },
  { id: 12, name: "يوسف", transliteration: "Yusuf", translation: "Joseph", type: "Meccan", ayahs: 111 },
  { id: 13, name: "الرعد", transliteration: "Ar-Ra'd", translation: "The Thunder", type: "Medinan", ayahs: 43 },
  { id: 14, name: "إبراهيم", transliteration: "Ibrahim", translation: "Abraham", type: "Meccan", ayahs: 52 },
  { id: 15, name: "الحجر", transliteration: "Al-Hijr", translation: "The Rocky Tract", type: "Meccan", ayahs: 99 },
  { id: 16, name: "النحل", transliteration: "An-Nahl", translation: "The Bee", type: "Meccan", ayahs: 128 },
  { id: 17, name: "الإسراء", transliteration: "Al-Isra", translation: "The Night Journey", type: "Meccan", ayahs: 111 },
  { id: 18, name: "الكهف", transliteration: "Al-Kahf", translation: "The Cave", type: "Meccan", ayahs: 110 },
  { id: 19, name: "مريم", transliteration: "Maryam", translation: "Mary", type: "Meccan", ayahs: 98 },
  { id: 20, name: "طه", transliteration: "Ta-Ha", translation: "Ta-Ha", type: "Meccan", ayahs: 135 },
  { id: 21, name: "الأنبياء", transliteration: "Al-Anbiya", translation: "The Prophets", type: "Meccan", ayahs: 112 },
  { id: 22, name: "الحج", transliteration: "Al-Hajj", translation: "The Pilgrimage", type: "Medinan", ayahs: 78 },
  { id: 23, name: "المؤمنون", transliteration: "Al-Mu'minun", translation: "The Believers", type: "Meccan", ayahs: 118 },
  { id: 24, name: "النور", transliteration: "An-Nur", translation: "The Light", type: "Medinan", ayahs: 64 },
  { id: 25, name: "الفرقان", transliteration: "Al-Furqan", translation: "The Criterion", type: "Meccan", ayahs: 77 },
  { id: 26, name: "الشعراء", transliteration: "Ash-Shu'ara", translation: "The Poets", type: "Meccan", ayahs: 227 },
  { id: 27, name: "النمل", transliteration: "An-Naml", translation: "The Ant", type: "Meccan", ayahs: 93 },
  { id: 28, name: "القصص", transliteration: "Al-Qasas", translation: "The Stories", type: "Meccan", ayahs: 88 },
  { id: 29, name: "العنكبوت", transliteration: "Al-Ankabut", translation: "The Spider", type: "Meccan", ayahs: 69 },
  { id: 30, name: "الروم", transliteration: "Ar-Rum", translation: "The Romans", type: "Meccan", ayahs: 60 },
  { id: 31, name: "لقمان", transliteration: "Luqman", translation: "Luqman", type: "Meccan", ayahs: 34 },
  { id: 32, name: "السجدة", transliteration: "As-Sajdah", translation: "The Prostration", type: "Meccan", ayahs: 30 },
  { id: 33, name: "الأحزاب", transliteration: "Al-Ahzab", translation: "The Combined Forces", type: "Medinan", ayahs: 73 },
  { id: 34, name: "سبأ", transliteration: "Saba", translation: "Sheba", type: "Meccan", ayahs: 54 },
  { id: 35, name: "فاطر", transliteration: "Fatir", translation: "Originator", type: "Meccan", ayahs: 45 },
  { id: 36, name: "يس", transliteration: "Ya-Sin", translation: "Ya Sin", type: "Meccan", ayahs: 83 },
  { id: 37, name: "الصافات", transliteration: "As-Saffat", translation: "Those who set the Ranks", type: "Meccan", ayahs: 182 },
  { id: 38, name: "ص", transliteration: "Sad", translation: "The Letter Sad", type: "Meccan", ayahs: 88 },
  { id: 39, name: "الزمر", transliteration: "Az-Zumar", translation: "The Troops", type: "Meccan", ayahs: 75 },
  { id: 40, name: "غافر", transliteration: "Ghafir", translation: "The Forgiver", type: "Meccan", ayahs: 85 },
  { id: 41, name: "فصلت", transliteration: "Fussilat", translation: "Explained in Detail", type: "Meccan", ayahs: 54 },
  { id: 42, name: "الشورى", transliteration: "Ash-Shura", translation: "The Consultation", type: "Meccan", ayahs: 53 },
  { id: 43, name: "الزخرف", transliteration: "Az-Zukhruf", translation: "The Ornaments of Gold", type: "Meccan", ayahs: 89 },
  { id: 44, name: "الدخان", transliteration: "Ad-Dukhan", translation: "The Smoke", type: "Meccan", ayahs: 59 },
  { id: 45, name: "الجاثية", transliteration: "Al-Jathiyah", translation: "The Crouching", type: "Meccan", ayahs: 37 },
  { id: 46, name: "الأحقاف", transliteration: "Al-Ahqaf", translation: "The Wind-Curved Sandhills", type: "Meccan", ayahs: 35 },
  { id: 47, name: "محمد", transliteration: "Muhammad", translation: "Muhammad", type: "Medinan", ayahs: 38 },
  { id: 48, name: "الفتح", transliteration: "Al-Fath", translation: "The Victory", type: "Medinan", ayahs: 29 },
  { id: 49, name: "الحجرات", transliteration: "Al-Hujurat", translation: "The Rooms", type: "Medinan", ayahs: 18 },
  { id: 50, name: "ق", transliteration: "Qaf", translation: "The Letter Qaf", type: "Meccan", ayahs: 45 },
  { id: 51, name: "الذاريات", transliteration: "Adh-Dhariyat", translation: "The Winnowing Winds", type: "Meccan", ayahs: 60 },
  { id: 52, name: "الطور", transliteration: "At-Tur", translation: "The Mount", type: "Meccan", ayahs: 49 },
  { id: 53, name: "النجم", transliteration: "An-Najm", translation: "The Star", type: "Meccan", ayahs: 62 },
  { id: 54, name: "القمر", transliteration: "Al-Qamar", translation: "The Moon", type: "Meccan", ayahs: 55 },
  { id: 55, name: "الرحمن", transliteration: "Ar-Rahman", translation: "The Beneficent", type: "Medinan", ayahs: 78 },
  { id: 56, name: "الواقعة", transliteration: "Al-Waqi'ah", translation: "The Inevitable", type: "Meccan", ayahs: 96 },
  { id: 57, name: "الحديد", transliteration: "Al-Hadid", translation: "The Iron", type: "Medinan", ayahs: 29 },
  { id: 58, name: "المجادلة", transliteration: "Al-Mujadila", translation: "The Pleading Woman", type: "Medinan", ayahs: 22 },
  { id: 59, name: "الحشر", transliteration: "Al-Hashr", translation: "The Exile", type: "Medinan", ayahs: 24 },
  { id: 60, name: "الممتحنة", transliteration: "Al-Mumtahanah", translation: "She that is to be Examined", type: "Medinan", ayahs: 13 },
  { id: 61, name: "الصف", transliteration: "As-Saf", translation: "The Ranks", type: "Medinan", ayahs: 14 },
  { id: 62, name: "الجمعة", transliteration: "Al-Jumu'ah", translation: "The Congregation", type: "Medinan", ayahs: 11 },
  { id: 63, name: "المنافقون", transliteration: "Al-Munafiqun", translation: "The Hypocrites", type: "Medinan", ayahs: 11 },
  { id: 64, name: "التغابن", transliteration: "At-Taghabun", translation: "The Mutual Disillusion", type: "Medinan", ayahs: 18 },
  { id: 65, name: "الطلاق", transliteration: "At-Talaq", translation: "The Divorce", type: "Medinan", ayahs: 12 },
  { id: 66, name: "التحريم", transliteration: "At-Tahrim", translation: "The Prohibition", type: "Medinan", ayahs: 12 },
  { id: 67, name: "الملك", transliteration: "Al-Mulk", translation: "The Sovereignty", type: "Meccan", ayahs: 30 },
  { id: 68, name: "القلم", transliteration: "Al-Qalam", translation: "The Pen", type: "Meccan", ayahs: 52 },
  { id: 69, name: "الحاقة", transliteration: "Al-Haqqah", translation: "The Reality", type: "Meccan", ayahs: 52 },
  { id: 70, name: "المعارج", transliteration: "Al-Ma'arij", translation: "The Ascending Stairways", type: "Meccan", ayahs: 44 },
  { id: 71, name: "نوح", transliteration: "Nuh", translation: "Noah", type: "Meccan", ayahs: 28 },
  { id: 72, name: "الجن", transliteration: "Al-Jinn", translation: "The Jinn", type: "Meccan", ayahs: 28 },
  { id: 73, name: "المزمل", transliteration: "Al-Muzzammil", translation: "The Enshrouded One", type: "Meccan", ayahs: 20 },
  { id: 74, name: "المدثر", transliteration: "Al-Muddaththir", translation: "The Cloaked One", type: "Meccan", ayahs: 56 },
  { id: 75, name: "القيامة", transliteration: "Al-Qiyamah", translation: "The Resurrection", type: "Meccan", ayahs: 40 },
  { id: 76, name: "الإنسان", transliteration: "Al-Insan", translation: "The Man", type: "Medinan", ayahs: 31 },
  { id: 77, name: "المرسلات", transliteration: "Al-Mursalat", translation: "The Emissaries", type: "Meccan", ayahs: 50 },
  { id: 78, name: "النبأ", transliteration: "An-Naba", translation: "The Tidings", type: "Meccan", ayahs: 40 },
  { id: 79, name: "النازعات", transliteration: "An-Nazi'at", translation: "Those who drag forth", type: "Meccan", ayahs: 46 },
  { id: 80, name: "عبس", transliteration: "Abasa", translation: "He Frowned", type: "Meccan", ayahs: 42 },
  { id: 81, name: "التكوير", transliteration: "At-Takwir", translation: "The Overthrowing", type: "Meccan", ayahs: 29 },
  { id: 82, name: "الانفطار", transliteration: "Al-Infitar", translation: "The Cleaving", type: "Meccan", ayahs: 19 },
  { id: 83, name: "المطففين", transliteration: "Al-Mutaffifin", translation: "The Defrauding", type: "Meccan", ayahs: 36 },
  { id: 84, name: "الانشقاق", transliteration: "Al-Inshiqaq", translation: "The Sundering", type: "Meccan", ayahs: 25 },
  { id: 85, name: "البروج", transliteration: "Al-Buruj", translation: "The Mansions of the Stars", type: "Meccan", ayahs: 22 },
  { id: 86, name: "الطارق", transliteration: "At-Tariq", translation: "The Nightcomer", type: "Meccan", ayahs: 17 },
  { id: 87, name: "الأعلى", transliteration: "Al-A'la", translation: "The Most High", type: "Meccan", ayahs: 19 },
  { id: 88, name: "الغاشية", transliteration: "Al-Ghashiyah", translation: "The Overwhelming", type: "Meccan", ayahs: 26 },
  { id: 89, name: "الفجر", transliteration: "Al-Fajr", translation: "The Dawn", type: "Meccan", ayahs: 30 },
  { id: 90, name: "البلد", transliteration: "Al-Balad", translation: "The City", type: "Meccan", ayahs: 20 },
  { id: 91, name: "الشمس", transliteration: "Ash-Shams", translation: "The Sun", type: "Meccan", ayahs: 15 },
  { id: 92, name: "الليل", transliteration: "Al-Layl", translation: "The Night", type: "Meccan", ayahs: 21 },
  { id: 93, name: "الضحى", transliteration: "Ad-Duha", translation: "The Morning Hours", type: "Meccan", ayahs: 11 },
  { id: 94, name: "الشرح", transliteration: "Ash-Sharh", translation: "The Relief", type: "Meccan", ayahs: 8 },
  { id: 95, name: "التين", transliteration: "At-Tin", translation: "The Fig", type: "Meccan", ayahs: 8 },
  { id: 96, name: "العلق", transliteration: "Al-Alaq", translation: "The Clot", type: "Meccan", ayahs: 19 },
  { id: 97, name: "القدر", transliteration: "Al-Qadr", translation: "The Power", type: "Meccan", ayahs: 5 },
  { id: 98, name: "البينة", transliteration: "Al-Bayyinah", translation: "The Clear Proof", type: "Medinan", ayahs: 8 },
  { id: 99, name: "الزلزلة", transliteration: "Az-Zalzalah", translation: "The Earthquake", type: "Medinan", ayahs: 8 },
  { id: 100, name: "العاديات", transliteration: "Al-Adiyat", translation: "The Coursers", type: "Meccan", ayahs: 11 },
  { id: 101, name: "القارعة", transliteration: "Al-Qari'ah", translation: "The Calamity", type: "Meccan", ayahs: 11 },
  { id: 102, name: "التكاثر", transliteration: "At-Takathur", translation: "The Rivalry in world increase", type: "Meccan", ayahs: 8 },
  { id: 103, name: "العصر", transliteration: "Al-Asr", translation: "The Declining Day", type: "Meccan", ayahs: 3 },
  { id: 104, name: "الهمزة", transliteration: "Al-Humazah", translation: "The Traducer", type: "Meccan", ayahs: 9 },
  { id: 105, name: "الفيل", transliteration: "Al-Fil", translation: "The Elephant", type: "Meccan", ayahs: 5 },
  { id: 106, name: "قريش", transliteration: "Quraysh", translation: "Quraysh", type: "Meccan", ayahs: 4 },
  { id: 107, name: "الماعون", transliteration: "Al-Ma'un", translation: "The Small Kindnesses", type: "Meccan", ayahs: 7 },
  { id: 108, name: "الكوثر", transliteration: "Al-Kawthar", translation: "The Abundance", type: "Meccan", ayahs: 3 },
  { id: 109, name: "الكافرون", transliteration: "Al-Kafirun", translation: "The Disbelievers", type: "Meccan", ayahs: 6 },
  { id: 110, name: "النصر", transliteration: "An-Nasr", translation: "The Divine Support", type: "Medinan", ayahs: 3 },
  { id: 111, name: "المسد", transliteration: "Al-Masad", translation: "The Palm Fibre", type: "Meccan", ayahs: 5 },
  { id: 112, name: "الإخلاص", transliteration: "Al-Ikhlas", translation: "The Sincerity", type: "Meccan", ayahs: 4 },
  { id: 113, name: "الفلق", transliteration: "Al-Falaq", translation: "The Daybreak", type: "Meccan", ayahs: 5 },
  { id: 114, name: "الناس", transliteration: "An-Nas", translation: "The Mankind", type: "Meccan", ayahs: 6 },
];
