/* ── Surah information dataset ───────────────────────────────────
   Static metadata for all 114 surahs: juz placement, name origin,
   thematic summary, and brief historical context.
──────────────────────────────────────────────────────────────── */

export interface SurahMeta {
  juz: number[];        // juz(es) this surah spans
  nameOrigin: string;   // etymology / origin of the surah name
  theme: string;        // 2–3 sentence thematic summary
  context: string;      // historical / circumstantial context
  notable?: string;     // optional notable feature or virtue
}

export const SURAH_INFO: Record<number, SurahMeta> = {
  1: {
    juz: [1],
    nameOrigin: "From fatḥ — 'to open'. The surah that opens the Quran.",
    theme: "The perfect prayer and declaration of servitude. Al-Fatiha encapsulates the entire relationship between the Creator and creation in seven verses: praise, sovereignty, worship, reliance, and supplication for guidance.",
    context: "Revealed in Makkah in the early period of Prophethood. Considered the first complete surah revealed, though some scholars hold that Iqra (96) was the first revelation.",
    notable: "Called Umm al-Quran (Mother of the Quran) and Sab'a al-Mathani (the seven oft-repeated verses). Recited in every unit of prayer.",
  },
  2: {
    juz: [1, 2, 3],
    nameOrigin: "Named for the story of the cow (al-baqara) commanded by Allah to be slaughtered by the Children of Israel (2:67–73).",
    theme: "The longest surah, covering the complete framework of Islamic law and theology: faith, worship, family law, business ethics, jihad, and the stories of previous nations. It establishes the Quran as the guide for those who are conscious of God.",
    context: "Revealed primarily in Madinah over many years after the Hijra. Addresses the newly formed Muslim community and challenges from the Jews and hypocrites of Madinah.",
    notable: "Contains Ayat al-Kursi (2:255), the greatest verse in the Quran. The last two verses (2:285–286) are reported to be a treasure from under the Throne of Allah.",
  },
  3: {
    juz: [3, 4],
    nameOrigin: "Named for the family of 'Imrān — father of Maryam and ancestor of Isa (Jesus).",
    theme: "Affirms the oneness of God and confronts the distortions in Christian and Jewish theology. Extensively covers the Battle of Uhud, lessons in patience and trust, and the status of Maryam and Isa.",
    context: "Revealed in Madinah, largely after the Battle of Uhud (3 AH) and during a period of dialogue with Christian delegations from Najran.",
    notable: "Verse 3:7 introduces the concept of the muhkam (clear) and mutashabih (ambiguous) verses of the Quran.",
  },
  4: {
    juz: [4, 5],
    nameOrigin: "Al-Nisa means 'The Women'. Named for its extensive legislation concerning women's rights and family matters.",
    theme: "Comprehensive legislation on family law, inheritance, marriage, and the rights of women and orphans. Also addresses the hypocrites, rules of prayer in fear, and the nature of Isa ibn Maryam.",
    context: "Revealed in Madinah after the Battle of Uhud (3–4 AH), when the Muslim community was dealing with large numbers of war orphans and widows.",
    notable: "Establishes the Islamic law of inheritance (4:11–12) and contains the verse of tayammum (dry ablution, 4:43).",
  },
  5: {
    juz: [6, 7],
    nameOrigin: "Al-Ma'ida — 'The Table Spread'. Named for the miraculous table of food requested by the disciples of Isa (5:112–115).",
    theme: "The final legislative surah, completing the obligations of the believers: contracts, food laws, wudu, hudud penalties, and alliances. It confirms the finality of the religion and God's pleasure with Islam.",
    context: "Among the last surahs revealed, in the period around the Farewell Pilgrimage (10 AH). Verse 5:3 ('Today I have perfected your religion') is believed to have been revealed at Arafat.",
    notable: "Contains the declaration that Islam is complete (5:3). One of the few surahs whose rulings are all considered to remain in force (none abrogated).",
  },
  6: {
    juz: [7, 8],
    nameOrigin: "Al-An'am — 'The Cattle'. Named for the mention of cattle and the pagan customs surrounding them (6:136–144).",
    theme: "A powerful Makkan argument for pure monotheism against idolatry. Uses rational proofs from creation, history, and the nature of revelation to demonstrate that Allah alone deserves worship.",
    context: "Revealed entirely in Makkah in the later Makkan period, reportedly revealed all at once accompanied by seventy thousand angels.",
    notable: "Contains the six 'grandly comprehensive' verses (6:151–153) that many scholars consider among the most important ethical directives in the Quran.",
  },
  7: {
    juz: [8, 9],
    nameOrigin: "Al-A'raf — the elevated place between Paradise and Hell where certain people will wait on the Day of Judgment.",
    theme: "A sweeping narrative of the human story: from the creation of Adam and Iblis's refusal to bow, through the missions of Nuh, Hud, Salih, Lut, Shu'ayb, and Musa, culminating in lessons on divine justice and the fate of nations.",
    context: "Revealed in Makkah in the middle-to-late Makkan period, as the Prophet ﷺ faced intensifying opposition.",
    notable: "The longest Makkan surah. The A'raf (heights) is described as a vantage point overlooking both Paradise and Hell.",
  },
  8: {
    juz: [9, 10],
    nameOrigin: "Al-Anfal — 'The Spoils of War'. Begins with the question of how to divide the booty from Badr.",
    theme: "Centers on the Battle of Badr (2 AH), the first major military engagement of the Muslims. Covers the ethics of war, the importance of unity, obedience to God and His Messenger, and the distribution of war gains.",
    context: "Revealed in Madinah immediately after the Battle of Badr (Ramadan, 2 AH), addressing both the spiritual and practical questions that arose from that momentous victory.",
    notable: "The verse 'O you who believe, respond to Allah and to the Messenger when he calls you to that which gives you life' (8:24) is considered one of the most comprehensive directives in the Quran.",
  },
  9: {
    juz: [10, 11],
    nameOrigin: "At-Tawba — 'The Repentance'. Also called Bara'a (Disavowal), being an ultimatum to the polytheists.",
    theme: "The most politically forceful surah — a declaration dissolving treaties with the polytheists and calling the hypocrites to account. Also covers the campaign of Tabuk, the virtue of the Companions, and sincere repentance.",
    context: "Revealed in Madinah in 9 AH, the Year of Delegations. The only surah not preceded by Bismillah, which scholars attribute to its stern opening tone.",
    notable: "The only surah without Bismillah at its start. Contains the Verse of the Sword (9:5) and the Verse of Difficulty (9:128–129).",
  },
  10: {
    juz: [11],
    nameOrigin: "Named for the Prophet Yunus (Jonah), whose story appears in verses 98–103.",
    theme: "Affirms divine sovereignty, the certainty of the Day of Judgment, and the truthfulness of Quranic revelation. Narrates the stories of Nuh, Musa, and Yunus as evidence that every nation received a messenger.",
    context: "Revealed in Makkah in the later Makkan period, as the Quraysh demanded miracles and challenged the Prophet ﷺ.",
    notable: "Verse 10:90 describes Pharaoh's last-moment declaration of faith — accepted for himself but too late to benefit him.",
  },
  11: {
    juz: [11, 12],
    nameOrigin: "Named for the Prophet Hud, who was sent to the people of 'Ad.",
    theme: "Commands the Prophet ﷺ to stand firm and be upright, using the stories of seven prophets — Nuh, Hud, Salih, Ibrahim, Lut, Shu'ayb, and Musa — as consolation and lessons on divine patience and retribution.",
    context: "Revealed in Makkah. Tradition states the Prophet ﷺ said this surah and its sister surahs 'turned my hair grey' because of its commands of steadfastness.",
    notable: "Verse 11:112, commanding complete uprightness (istiqama), was described by the Prophet ﷺ as having aged him.",
  },
  12: {
    juz: [12, 13],
    nameOrigin: "Named entirely for the Prophet Yusuf (Joseph), whose complete story is told within it.",
    theme: "The most complete narrative in the Quran — the life of Yusuf from childhood to his rise as a minister in Egypt. Themes include patience in adversity, chastity, forgiveness, and divine planning.",
    context: "Revealed in Makkah, in the Year of Sorrow, after the deaths of Khadija and Abu Talib. Called 'ahsan al-qasas' — the best of stories.",
    notable: "The Quran describes it as 'the best of stories' (12:3). Its revelation was a source of consolation to the Prophet ﷺ in his time of grief.",
  },
  13: {
    juz: [13],
    nameOrigin: "Ar-Ra'd — 'The Thunder'. Named for the mention of thunder glorifying Allah (13:13).",
    theme: "Affirms the reality of revelation, divine knowledge, and the certainty of resurrection. Uses natural phenomena — thunder, lightning, rain, rivers — as signs of divine power and mercy.",
    context: "Believed to be Makkan in origin, though some verses may have been revealed in Madinah.",
    notable: "Contains the verse: 'Indeed, Allah does not change the condition of a people until they change what is in themselves' (13:11).",
  },
  14: {
    juz: [13],
    nameOrigin: "Named for Ibrahim (Abraham), whose supplication is quoted at length (14:35–41).",
    theme: "Reflects on the purpose of divine messengers — to bring people from darkness into light. Features Ibrahim's prayer for Makkah and his descendants, and vivid descriptions of the consequences of gratitude and ingratitude.",
    context: "Revealed in Makkah. The imagery of a good word as a good tree and an evil word as an evil tree (14:24–26) is among the Quran's most celebrated parables.",
    notable: "Ibrahim's prayer for the believers (14:40–41) is widely recited as a personal supplication.",
  },
  15: {
    juz: [14],
    nameOrigin: "Al-Hijr — the rocky tract, a region inhabited by the people of Thamud to whom Salih was sent.",
    theme: "Reassures the Prophet ﷺ against the mockery of the disbelievers by recounting the stories of earlier prophets. Affirms divine protection of the Quran and the story of Iblis's arrogance.",
    context: "Revealed in Makkah as the Prophet ﷺ faced ridicule and rejection from the Quraysh.",
    notable: "Verse 15:9 — 'Indeed, it is We who have sent down the Quran and indeed, We will be its guardian' — is the divine guarantee of the Quran's preservation.",
  },
  16: {
    juz: [14],
    nameOrigin: "An-Nahl — 'The Bee'. Named for the bee's remarkable instinct as a sign of divine wisdom (16:68–69).",
    theme: "An extensive catalogue of divine blessings — animals, crops, rivers, shade, ships — calling humanity to gratitude. Also covers the permissibility of necessities, the prohibition of lying about Allah, and the obligation of migrating from oppression.",
    context: "Mostly Makkan, with some Medinan verses at the end (16:126–128). Covers a period when many Muslims were migrating to Abyssinia.",
    notable: "Contains the verse of consultation and command: 'Indeed, Allah orders justice and good conduct and giving to relatives' (16:90), recited by imams in Friday khutbahs.",
  },
  17: {
    juz: [15],
    nameOrigin: "Al-Isra — 'The Night Journey'. Named for the miraculous night journey of the Prophet ﷺ from Makkah to Jerusalem.",
    theme: "Opens with the Isra (Night Journey) and presents seventeen ethical commandments on worship, parents, wealth, and integrity. Addresses the Quran's miracle, the fall of Iblis, and the fate of the Children of Israel.",
    context: "Revealed in the late Makkan period. The Isra is one of the most significant events in prophetic biography.",
    notable: "Contains the seventeen commandments of the Quran (17:22–39) — a comprehensive moral charter covering all dimensions of life.",
  },
  18: {
    juz: [15, 16],
    nameOrigin: "Al-Kahf — 'The Cave'. Named for the story of the young men who took refuge in a cave from religious persecution.",
    theme: "Four stories as remedies against four forms of trial: the People of the Cave (trial of religion), Dhul-Qarnayn (trial of power), the two garden owners (trial of wealth), and Musa and Khidr (trial of knowledge).",
    context: "Revealed in Makkah when the Quraysh asked the Prophet ﷺ questions suggested by rabbis in Madinah, testing his prophethood.",
    notable: "The Prophet ﷺ recommended reciting this surah every Friday as protection from the trials of the Dajjal. The first and last ten verses provide specific protection.",
  },
  19: {
    juz: [16],
    nameOrigin: "Named for Maryam (Mary), mother of Isa (Jesus), who is the only woman named in the Quran.",
    theme: "Presents the miraculous births of Yahya (John the Baptist) and Isa (Jesus), the piety of Maryam, and a series of prophetic biographies. Affirms that it is not befitting for Allah to take a son.",
    context: "Revealed in Makkah. When the first group of Muslims migrated to Abyssinia, Ja'far ibn Abi Talib recited verses from this surah to the Christian king Negus.",
    notable: "Maryam is the only woman honoured with a surah named after her in the Quran.",
  },
  20: {
    juz: [16],
    nameOrigin: "Ta-Ha — two Arabic letters (muqatta'at) whose precise meaning is known only to Allah.",
    theme: "An extended, eloquent account of the story of Musa — his divine commission, his mission to Pharaoh, the miracles, and the exodus. Also addresses Adam's trial and the Day of Judgment.",
    context: "Revealed in the late Makkan period. Tradition records that Umar ibn al-Khattab began reading this surah and was moved to accept Islam.",
    notable: "Verse 20:14 — 'Indeed, I am Allah. There is no god but Me, so worship Me and establish prayer for My remembrance' — is one of the clearest divine self-declarations in the Quran.",
  },
  21: {
    juz: [17],
    nameOrigin: "Al-Anbiya — 'The Prophets'. Named for the many prophets mentioned in this surah.",
    theme: "Draws on the stories of eighteen prophets — Ibrahim, Lut, Nuh, Dawud, Sulayman, Ayyub, Yunus, Zakariyya, Yahya — to show that all messengers called to the same truth: monotheism and accountability.",
    context: "Revealed in Makkah as the opposition to the Prophet ﷺ intensified.",
    notable: "Verse 21:107 — 'And We have not sent you except as a mercy to the worlds' — is one of the most beloved descriptions of the Prophet ﷺ.",
  },
  22: {
    juz: [17],
    nameOrigin: "Al-Hajj — 'The Pilgrimage'. Named for the institution of the Hajj described in this surah.",
    theme: "Covers the Hajj and its spiritual significance, the Day of Judgment and its cosmic scale, the legitimacy of defending oneself, and proofs of resurrection in the natural world.",
    context: "Mixed Makkan and Medinan revelation. One of the few surahs that contains a verse (22:19) where prostration is obligatory (sajdah al-tilawa).",
    notable: "Verses 22:25–37 provide the foundational legislation for Hajj. This surah has two verses of prostration according to some scholars.",
  },
  23: {
    juz: [18],
    nameOrigin: "Al-Mu'minun — 'The Believers'. Named for its opening description of the qualities of true believers.",
    theme: "Opens with a portrait of the successful believer — humble in prayer, avoiding idle speech, giving zakah, chaste, and trustworthy. Continues with the stages of human creation, the missions of earlier prophets, and a warning against heedlessness.",
    context: "Revealed in Makkah. The Imam Ahmad ibn Hanbal would often recite the opening ten verses and then weep.",
    notable: "The opening ten verses (23:1–10) describing the successful believers are among the most celebrated in the Quran and widely memorised.",
  },
  24: {
    juz: [18],
    nameOrigin: "An-Nur — 'The Light'. Named for the magnificent Light Verse (24:35) describing Allah's light.",
    theme: "Primarily legislative: laws concerning chastity, the punishment for adultery, the code of conduct around slander, rules of dress and modesty, and protocols for entering homes. Anchored by the sublime Light Verse.",
    context: "Revealed in Madinah largely in response to the incident of the slander against Aisha (the Ifk affair, 5 AH).",
    notable: "Ayat al-Nur (24:35) — 'Allah is the Light of the heavens and the earth' — is one of the most commented-upon verses in the Quran.",
  },
  25: {
    juz: [18, 19],
    nameOrigin: "Al-Furqan — 'The Criterion'. One of the names of the Quran, meaning that which distinguishes truth from falsehood.",
    theme: "Refutes the objections of the disbelievers against the Quran and the Prophet ﷺ, presents signs of divine power in creation, and concludes with a beautiful portrait of the 'servants of the Most Merciful' ('Ibad ar-Rahman).",
    context: "Revealed in Makkah. The closing portrait of the true believers (25:63–77) is widely memorised.",
    notable: "The description of 'Ibad ar-Rahman (25:63–77) — those who walk humbly, avoid evil, guard their prayers — is a comprehensive portrait of the ideal Muslim character.",
  },
  26: {
    juz: [19],
    nameOrigin: "Ash-Shu'ara — 'The Poets'. Named for the final passage distinguishing the Quran from poetry (26:224–227).",
    theme: "A series of eleven prophetic narratives — Musa, Ibrahim, Nuh, Hud, Salih, Lut, Shu'ayb — each following the same pattern: mission, rejection, punishment of the disbelievers, salvation of the believers.",
    context: "Revealed in Makkah. The repetitive structure reflects the Quran's rhetorical emphasis and serves as a mnemonic for the universal pattern of prophethood.",
    notable: "The repeated refrain 'And indeed, your Lord — He is the Exalted in Might, the Merciful' (repeated 8 times) underscores the balance of divine power and mercy.",
  },
  27: {
    juz: [19, 20],
    nameOrigin: "An-Naml — 'The Ant'. Named for the valley of ants whose conversation Sulayman miraculously overheard.",
    theme: "Features the stories of Musa, Sulayman (including the Queen of Sheba), Salih, and Lut. Presents signs of divine knowledge and power, and offers a remarkable argument for monotheism through comparison with the powerlessness of idols.",
    context: "Revealed in Makkah. The story of Sulayman and Bilqis (Queen of Sheba) is the most detailed account of Sulayman's kingdom in the Quran.",
    notable: "Verse 27:88 — 'And you see the mountains thinking them fixed, while they will pass as the passing of clouds' — is interpreted by many as a reference to the movement of the earth.",
  },
  28: {
    juz: [20],
    nameOrigin: "Al-Qasas — 'The Stories/Narrations'. Named for the word qasas meaning stories or narrations.",
    theme: "The most complete telling of Musa's life — from his birth and survival in the Nile, through his youth in Pharaoh's palace, his exile to Madyan, his return with prophethood, to the defeat of Pharaoh. Also features the story of Qarun.",
    context: "Revealed in Makkah. Believed to have been revealed as the Prophet ﷺ departed Makkah for Madinah, with the promise of return (28:85).",
    notable: "Verse 28:85 — 'Indeed, He who imposed upon you the Quran will take you back to a place of return' — is traditionally understood as a promise of the Prophet's return to Makkah.",
  },
  29: {
    juz: [20, 21],
    nameOrigin: "Al-Ankabut — 'The Spider'. Named for the parable of the spider's web as a symbol of the fragility of false religion.",
    theme: "Opens with the theme of trial and testing — that belief must be proven through hardship. Narrates the stories of Nuh, Ibrahim, Lut, Shu'ayb, Hud, Salih, and Musa. Uses the spider's web to illustrate the weakness of polytheism.",
    context: "Revealed partly in Makkah and partly in Madinah, during a period when many believers were persecuted.",
    notable: "Verse 29:45 — 'Recite what has been revealed to you of the Book and establish prayer. Indeed, prayer prohibits immorality and wrongdoing' — describes the preventive role of salah.",
  },
  30: {
    juz: [21],
    nameOrigin: "Ar-Rum — 'The Romans (Byzantines)'. Named for the prediction of a Byzantine victory over the Persians.",
    theme: "Opens with one of the Quran's few historical predictions — the Byzantine defeat and eventual victory — as a sign of divine knowledge. Reflects on the signs of Allah in creation, the resurrection, and the nature of gratitude and ingratitude.",
    context: "Revealed in Makkah around 615 CE when the Persians had just defeated the Byzantines. The prediction of a Byzantine comeback within nine years was fulfilled at the Battle of Nineveh (627 CE).",
    notable: "The prophecy of 30:2–5 was fulfilled precisely, and the Muslims won at Badr the same day the Byzantines won their victory — a double cause for rejoicing.",
  },
  31: {
    juz: [21],
    nameOrigin: "Named for Luqman, a wise man (not a prophet) renowned for his wisdom, whose advice to his son is quoted.",
    theme: "Features the wisdom of Luqman as a model for parents and children — gratitude to Allah and parents, avoiding shirk, humility, patience, and respect. Bookended by the majesty of the Quran and the unknowability of the Last Hour.",
    context: "Revealed in Makkah.",
    notable: "Luqman's advice (31:13–19) is considered a comprehensive moral curriculum from parent to child.",
  },
  32: {
    juz: [21],
    nameOrigin: "As-Sajdah — 'The Prostration'. Named for the verse of prostration (32:15).",
    theme: "Affirms the divine origin of the Quran, the reality of creation in six days, and the stages of human creation. Contrasts the humility of the believers with the arrogance of the deniers, and describes the rewards of the pious.",
    context: "Revealed in Makkah. The Prophet ﷺ would recite this surah along with Al-Mulk (67) every night before sleeping.",
    notable: "Recommended to be recited at Fajr on Fridays along with Surah Al-Insan (76).",
  },
  33: {
    juz: [21, 22],
    nameOrigin: "Al-Ahzab — 'The Confederate Tribes'. Named for the allied forces that besieged Madinah in the Battle of the Trench.",
    theme: "Covers the Battle of the Trench (Ahzab, 5 AH) and its aftermath, the rulings of adoption, the marriages of the Prophet ﷺ, the special obligations of the Prophet's wives, hijab legislation, and the offer of the divine trust (amanah).",
    context: "Revealed in Madinah, addressing critical events of the fifth year after Hijra.",
    notable: "Verse 33:56 — 'Indeed, Allah and His angels send blessings upon the Prophet. O you who believe, ask Allah to confer blessing upon him' — is the basis for sending salawat.",
  },
  34: {
    juz: [22],
    nameOrigin: "Saba — named for the kingdom of Sheba (Saba'), mentioned in the story of Sulayman and the Queen of Sheba.",
    theme: "Addresses those who deny the resurrection and prophethood. Uses the examples of Dawud and Sulayman's blessings and the downfall of Saba to show that divine favour comes with gratitude and divine punishment with ingratitude.",
    context: "Revealed in Makkah.",
    notable: "The story of Saba (34:15–19) is a historical example of a prosperous civilisation destroyed by ingratitude.",
  },
  35: {
    juz: [22],
    nameOrigin: "Fatir — 'The Originator/Creator'. Named for the first verse describing Allah as the Originator of the heavens and earth.",
    theme: "Presents the majesty of Allah as creator and sustainer against the powerlessness of false gods. Draws on signs in nature — rain, trees, colours, mountains, seas — as evidence of divine lordship. Describes the diversity of creation and the ranks of the learned.",
    context: "Revealed in Makkah.",
    notable: "Verse 35:28 — 'Only those fear Allah, from among His servants, who have knowledge' — affirms that true learning leads to God-consciousness.",
  },
  36: {
    juz: [22, 23],
    nameOrigin: "Ya-Sin — two muqatta'at (disjointed letters) considered by many scholars as one of the names of the Prophet ﷺ.",
    theme: "Often called the 'heart of the Quran'. Presents a parable of an ancient city that rejected its messengers, followed by arguments for resurrection from the signs of agriculture, ships, and night and day, and an account of the Day of Judgment.",
    context: "Revealed in Makkah. The Prophet ﷺ described it as 'the heart of the Quran' and recommended reciting it for the dying.",
    notable: "Called 'Qalb al-Quran' (Heart of the Quran) by the Prophet ﷺ. Traditionally recited for those approaching death.",
  },
  37: {
    juz: [23],
    nameOrigin: "As-Saffat — 'Those who line up/rank'. Named for the opening oath by the angels who line up in rows.",
    theme: "Uses a series of oaths to affirm the oneness of Allah and the Day of Judgment. Features the stories of Ibrahim's test with his son, Musa, Harun, Ilyas, Lut, and Yunus — all as proofs that prophets are vindicated and their opponents destroyed.",
    context: "Revealed in Makkah.",
    notable: "The story of Ibrahim's test (37:100–113) — the near-sacrifice of his son — is narrated here most completely in the Quran.",
  },
  38: {
    juz: [23],
    nameOrigin: "Sad — a single muqatta'a letter. Some scholars associate it with one of the names of the Quran.",
    theme: "Addresses the Prophet ﷺ, comparing his persecution to that of Dawud, Sulayman, and Ayyub — all of whom were tested and ultimately vindicated. Contrasts the arrogance of the disbelievers with the humility of the prophets.",
    context: "Revealed in Makkah, when tribal leaders were pressuring Abu Talib to withdraw his protection from the Prophet ﷺ.",
    notable: "Contains the story of Iblis's defiance (38:71–85) in detailed dialogue form.",
  },
  39: {
    juz: [23, 24],
    nameOrigin: "Az-Zumar — 'The Groups/Crowds'. Named for the groups of people driven to Hell and to Paradise on the Day of Judgment.",
    theme: "A powerful call to sincere monotheism, rejecting hypocrisy and polytheism. Features the parable of a slave with many masters versus one master, the stages of sleep and death, and vivid scenes of the Day of Judgment.",
    context: "Revealed in Makkah, though some scholars consider a few verses Medinan.",
    notable: "Verse 39:53 — 'Do not despair of the mercy of Allah. Indeed, Allah forgives all sins' — is one of the most hope-giving verses in the Quran.",
  },
  40: {
    juz: [24],
    nameOrigin: "Ghafir — 'The Forgiver'. Named for the divine attribute of forgiveness mentioned in the opening verses.",
    theme: "Begins the Hawamim surahs (40–46). A believing man from among Pharaoh's family argues secretly for Musa and is a model of courage. Presents extensive descriptions of the Day of Judgment and divine power over creation.",
    context: "Revealed in Makkah. Also known as Surah al-Mu'min (The Believer).",
    notable: "The believer from the family of Pharaoh (40:28–44) is unnamed in the Quran but has been called 'the believer of the family of Pharaoh' — a symbol of standing for truth at personal risk.",
  },
  41: {
    juz: [24, 25],
    nameOrigin: "Fussilat — 'Explained in Detail'. Named for the divine description of the Quran as a book whose verses are detailed (41:3).",
    theme: "Addresses the disbelievers' rejection of the Quran, describing how the very limbs of the body will testify against the sinner on the Day of Judgment. Uses the signs of creation — earth, sky, mountains — as evidence of divine power.",
    context: "Revealed in Makkah.",
    notable: "Verse 41:30 — 'Indeed, those who have said: Our Lord is Allah — and then remained firm — the angels will descend upon them' — is a profound verse on steadfastness.",
  },
  42: {
    juz: [25],
    nameOrigin: "Ash-Shura — 'The Consultation'. Named for the mention of mutual consultation (shura) among the believers.",
    theme: "Affirms divine revelation across all prophets and the unity of all religions under one God. Stresses that differences among people are by divine will. Presents consultation, forgiveness, and avoidance of excess as defining features of the believers.",
    context: "Revealed in Makkah.",
    notable: "Verse 42:38 — including 'their affairs are decided by mutual consultation' — has been cited as a Quranic basis for participatory governance.",
  },
  43: {
    juz: [25],
    nameOrigin: "Az-Zukhruf — 'The Gold Adornments'. Named for the golden adornments of worldly wealth mentioned in the surah.",
    theme: "Contrasts the fleeting value of worldly wealth with the eternal rewards of faith. Features the stories of Ibrahim's rejection of his people's idols and Musa's challenge to Pharaoh. Criticises those who follow ancestors blindly without reflection.",
    context: "Revealed in Makkah.",
    notable: "Contains a description of the believers' rejoicing in Paradise (43:68–73) and the repeated refrain of the polytheists justifying idolatry through ancestral tradition.",
  },
  44: {
    juz: [25],
    nameOrigin: "Ad-Dukhan — 'The Smoke'. Named for the smoke that will appear on the Day of Judgment as one of its signs.",
    theme: "A short but powerful surah revealed in a night of blessing. Warns of the smoke of the Day of Judgment, contrasts the fate of the people of Pharaoh with the joy of the believers, and affirms the Quran's divine origin.",
    context: "Revealed in Makkah. The Prophet ﷺ recommended its recitation on Friday nights.",
    notable: "Recommended by the Prophet ﷺ for Thursday nights. Contains the magnificent description of the night of the Quran's revelation (44:3–4).",
  },
  45: {
    juz: [25],
    nameOrigin: "Al-Jathiya — 'The Kneeling'. Named for the scene of every nation kneeling before Allah on the Day of Judgment.",
    theme: "Calls on humanity to reflect on the signs in creation — animals, seas, night and day — as proofs of divine power. Warns those who follow whims over divine guidance, and describes the final accounting of all communities.",
    context: "Revealed in Makkah.",
    notable: "Verse 45:23 — 'Have you seen him who takes as his god his own desire?' — is a powerful critique of moral relativism.",
  },
  46: {
    juz: [26],
    nameOrigin: "Al-Ahqaf — the region of sand dunes in Arabia where the people of 'Ad lived.",
    theme: "Affirms the divine origin of the Quran and warns of the fate of the people of 'Ad as a lesson for the Quraysh. Features a remarkable account of jinns who heard the Quran and embraced Islam, and a moving call to honour one's parents.",
    context: "Revealed in Makkah, the last of the Hawamim surahs.",
    notable: "Verses 46:29–32 describe the jinns listening to the Quran and accepting Islam — one of two accounts of this event in the Quran.",
  },
  47: {
    juz: [26],
    nameOrigin: "Named for Muhammad ﷺ, whose name appears in verse 47:2. Also known as Al-Qital (Fighting).",
    theme: "Addresses the believers on the occasion of armed conflict — commanding firm resolve, forbidding making peace with the disbelievers out of weakness, and warning the hypocrites who harboured doubts about fighting.",
    context: "Revealed in Madinah, likely around the time of the Battle of Badr or Uhud.",
    notable: "One of only four places the Prophet's name 'Muhammad' appears in the Quran.",
  },
  48: {
    juz: [26],
    nameOrigin: "Al-Fath — 'The Victory'. Named for the 'clear victory' — referring to the Treaty of Hudaybiyyah.",
    theme: "Declares the Treaty of Hudaybiyyah (6 AH) a manifest victory, even though it appeared to be a compromise. Praises the believers who pledged allegiance under the tree, and predicts the future conquest of Makkah and Persia.",
    context: "Revealed in Madinah immediately after the Treaty of Hudaybiyyah (6 AH). The Prophet ﷺ said this surah was dearer to him than the whole world.",
    notable: "The Treaty of Hudaybiyyah, though appearing a setback, led directly to the conquest of Makkah two years later.",
  },
  49: {
    juz: [26],
    nameOrigin: "Al-Hujurat — 'The Private Apartments'. Named for the reference to those who call the Prophet ﷺ from outside his private rooms.",
    theme: "A masterclass in Islamic social ethics: not preceding Allah and His Messenger, verifying news before acting on it, not mocking others, avoiding suspicion and spying, reconciling between Muslims, and affirming the brotherhood of all believers.",
    context: "Revealed in Madinah. One of the most socially instructive surahs.",
    notable: "Verse 49:12 — forbidding suspicion, spying, and backbiting — and 49:13 — affirming human brotherhood across races — are among the most cited in Islamic ethics.",
  },
  50: {
    juz: [26],
    nameOrigin: "Qaf — a muqatta'a letter. The Prophet ﷺ used to recite this surah in the Eid and Friday prayers.",
    theme: "Powerfully confronts the disbelievers' denial of resurrection. Uses the miracle of rain reviving dead earth as an analogy for the resurrection of the dead. Describes the closeness of angels, the dying moment, and the Day of Judgment.",
    context: "Revealed in Makkah.",
    notable: "The Prophet ﷺ would regularly recite this surah at Friday prayers and on Eid, due to its comprehensive reminder of resurrection and divine presence.",
  },
  51: {
    juz: [26, 27],
    nameOrigin: "Adh-Dhariyat — 'The Winds that Scatter'. Named for the oath by the scattering winds.",
    theme: "Opens with four cosmic oaths affirming divine promise. Narrates the stories of Ibrahim, Musa, 'Ad, Thamud, and Nuh as warnings. Concludes with the fundamental truth: creation was made only to worship Allah.",
    context: "Revealed in Makkah.",
    notable: "Verse 51:56 — 'I did not create jinn and humans except to worship Me' — is the definitive statement on the purpose of creation.",
  },
  52: {
    juz: [27],
    nameOrigin: "At-Tur — 'The Mountain (Sinai)'. Named for the oath by Mount Sinai.",
    theme: "Opens with five cosmic oaths affirming that divine punishment is inevitable. Describes the joy of the believers in Paradise and refutes the disbelievers' objections to the Prophet ﷺ. Ends with a command to the Prophet ﷺ to be patient.",
    context: "Revealed in Makkah. Ibn 'Abbas narrated that listening to this surah had a profound effect on 'Umar ibn al-Khattab.",
    notable: "Verse 52:21 — 'We will join with them their descendants who followed them in faith' — assures believers that faithful families will be reunited in Paradise.",
  },
  53: {
    juz: [27],
    nameOrigin: "An-Najm — 'The Star'. Named for the opening oath: 'By the star when it descends.'",
    theme: "Describes the Prophet's ﷺ direct experience of revelation — the Night Journey and his vision of the Archangel Jibril. Refutes the divinity of the pagan goddesses al-Lat, al-Uzza, and Manat. Asserts that guidance and misguiding come from Allah alone.",
    context: "Revealed in Makkah. This is the first surah to be publicly recited in the Ka'ba. When the Prophet ﷺ reached the prostration verse, all present — believers and disbelievers alike — fell into prostration.",
    notable: "The occasion of the first public recitation in the Ka'ba, at which all present prostrated (the sajdah at 53:62).",
  },
  54: {
    juz: [27],
    nameOrigin: "Al-Qamar — 'The Moon'. Named for the miraculous splitting of the moon (54:1–2).",
    theme: "Opens with the sign of the split moon. Uses the stories of the people of Nuh, 'Ad, Thamud, Lut, and Pharaoh — each followed by the refrain 'Is there any who will remember?' — to warn of the swift punishment that struck those who denied.",
    context: "Revealed in Makkah. The splitting of the moon is one of the acknowledged miracles of the Prophet ﷺ.",
    notable: "The refrain 'We have made the Quran easy to remember — is there any who will remember?' (repeated four times) is a divine guarantee of the Quran's accessibility.",
  },
  55: {
    juz: [27],
    nameOrigin: "Ar-Rahman — 'The Most Merciful'. The surah is defined by the divine name it centres on.",
    theme: "A lyrical celebration of divine mercy and blessing. Catalogues the gifts of creation — the Quran, humanity, the sun and moon, plants, sky, and the two seas — with the refrain 'Which of your Lord's blessings do you both deny?'",
    context: "Revelation period debated: some say Makkan, others Medinan. The repeated refrain (occurring 31 times) makes it one of the most memorable surahs.",
    notable: "The refrain 'Fa-bi-ayyi ala'i rabbikuma tukadhdhibaan' — 'Which of your Lord's blessings do you both deny?' — repeats 31 times.",
  },
  56: {
    juz: [27],
    nameOrigin: "Al-Waqi'a — 'The Inevitable Event'. Named for the Day of Judgment as the event that will inevitably come.",
    theme: "Divides humanity into three groups on the Day of Judgment: the foremost (Sabiqun), the people of the right, and the people of the left. Describes their respective rewards and punishments in vivid detail, and ends with a statement of the Quran's sacred origin.",
    context: "Revealed in Makkah.",
    notable: "Verse 56:79 — 'None touch it except the purified' — is cited as evidence for the requirement of ritual purity when handling the Quran.",
  },
  57: {
    juz: [27],
    nameOrigin: "Al-Hadid — 'The Iron'. Named for the verse describing iron as a gift from Allah (57:25).",
    theme: "Calls the believers to spend in the way of Allah with urgency, before death arrives. Reflects on the brevity of worldly life and the vastness of divine knowledge. Mentions the Prophet Isa and the institution of monasticism.",
    context: "Revealed in Madinah. One of the Musabbihat surahs (opening with glorification of Allah).",
    notable: "Verse 57:4 — 'He is with you wherever you are' — is one of the most direct Quranic statements on divine omnipresence.",
  },
  58: {
    juz: [28],
    nameOrigin: "Al-Mujadila — 'The Pleading Woman'. Named for the woman who pleaded her case to the Prophet ﷺ.",
    theme: "Opens by addressing the case of a woman whose husband used the pre-Islamic divorce formula of zihar. Covers the prohibition of this practice, the rulings of secret meetings, and a strong condemnation of befriending enemies of Allah.",
    context: "Revealed in Madinah in response to a specific case involving Khawla bint Tha'laba.",
    notable: "The surah opens with the remarkable divine attentiveness: 'Allah has heard the statement of the one who argues with you concerning her husband.' — affirming that no prayer goes unheard.",
  },
  59: {
    juz: [28],
    nameOrigin: "Al-Hashr — 'The Exile'. Named for the expulsion of the Banu Nadir Jewish tribe from Madinah.",
    theme: "Describes the expulsion of the Banu Nadir from Madinah for their betrayal of the treaty with the Prophet ﷺ. Covers the distribution of the gains, the qualities of the emigrants and helpers, and the magnificent closing passage on the names of Allah.",
    context: "Revealed in Madinah, 4 AH, after the expulsion of the Banu Nadir.",
    notable: "The closing verses (59:22–24) contain one of the Quran's most concentrated descriptions of the divine names and attributes. Widely recited as a morning remembrance.",
  },
  60: {
    juz: [28],
    nameOrigin: "Al-Mumtahina — 'The Woman to be Examined'. Named for the procedure of examining women migrants for sincerity of faith.",
    theme: "Commands the believers not to take the enemies of Allah as close allies, using Ibrahim's example. Establishes protocols for receiving believing women migrants, treaty relations with peaceful non-Muslims, and maintaining family bonds wisely.",
    context: "Revealed in Madinah, in the period after Hudaybiyyah (6 AH).",
    notable: "Verse 60:8 — 'Allah does not forbid you from those who do not fight you in religion and do not expel you from your homes — that you be righteous toward them and act justly' — is a key verse on Islam's approach to peaceful non-Muslims.",
  },
  61: {
    juz: [28],
    nameOrigin: "As-Saf — 'The Row/Rank'. Named for the believers who fight in ranks like a solid structure.",
    theme: "Calls the believers to align their words with their deeds, and to support the cause of Allah as the disciples of Isa did. Features Isa's prophecy of the coming of Ahmad (the Prophet Muhammad ﷺ).",
    context: "Revealed in Madinah.",
    notable: "Verse 61:6 — Isa's prophecy of 'Ahmad' to come after him — is one of the Quranic references to the Prophet Muhammad's name.",
  },
  62: {
    juz: [28],
    nameOrigin: "Al-Jumu'a — 'Friday'. Named for the command to hasten to Friday prayer.",
    theme: "Celebrates the sending of the Prophet ﷺ as a mercy to an unlettered people, and legislates the obligation of the Friday prayer — commanding believers to leave trade and hasten to Allah's remembrance.",
    context: "Revealed in Madinah. Contains the legal foundation for the Friday jumu'ah prayer.",
    notable: "Verse 62:9 — commanding leaving of business for Friday prayer — established one of Islam's most enduring congregational obligations.",
  },
  63: {
    juz: [28],
    nameOrigin: "Al-Munafiqun — 'The Hypocrites'. Named for its subject: the hypocrites of Madinah.",
    theme: "Exposes the characteristics of the hypocrites — their eloquent falsehood, their obstruction of charity, their arrogance, and their unwillingness to seek forgiveness. Warns the believers not to let wealth and children distract them from Allah.",
    context: "Revealed in Madinah. Related to incidents involving Abdullah ibn Ubayy, the chief of the hypocrites.",
    notable: "The contrast between the hypocrites' confident eloquence and their hollow hearts is one of the Quran's most incisive social critiques.",
  },
  64: {
    juz: [28],
    nameOrigin: "At-Taghabun — 'The Mutual Disillusionment'. Named for the Day when people will recognise their losses.",
    theme: "Affirms divine knowledge and sovereignty, the necessity of trial, and the reality of the Day of Accounting. Reminds the believers that spouses and children can be trials, and commands spending generously and obeying Allah and His Messenger.",
    context: "Revealed in Madinah. One of the Musabbihat surahs.",
    notable: "Verse 64:11 — 'No disaster strikes except by permission of Allah. And whoever believes in Allah — He will guide his heart' — is a key verse on accepting divine decree.",
  },
  65: {
    juz: [28],
    nameOrigin: "At-Talaq — 'Divorce'. Named for its comprehensive legislation on divorce and the waiting period.",
    theme: "Detailed legislation on divorce — the waiting period, the maintenance of divorced wives, nursing agreements, and God-consciousness throughout the process. Ends with a reminder of divine knowledge and omnipotence.",
    context: "Revealed in Madinah. Sometimes called the 'Little Surah An-Nisa' for its legislative content concerning women.",
    notable: "Verse 65:3 — 'And whoever relies upon Allah — then He is sufficient for him' — is one of the most cited verses of trust (tawakkul) in the Quran.",
  },
  66: {
    juz: [28],
    nameOrigin: "At-Tahrim — 'The Prohibition'. Named for the Prophet's ﷺ prohibiting something permissible upon himself.",
    theme: "Begins with a gentle correction of the Prophet ﷺ for prohibiting something Allah made lawful. Warns the believers to protect themselves and their families from the Fire. Uses the contrasting examples of the wives of Nuh and Lut versus the wife of Pharaoh and Maryam.",
    context: "Revealed in Madinah.",
    notable: "Verse 66:6 — 'O you who believe, protect yourselves and your families from a Fire' — is the Quranic foundation for Islamic family education.",
  },
  67: {
    juz: [29],
    nameOrigin: "Al-Mulk — 'The Sovereignty/Dominion'. Named for the opening declaration that all dominion belongs to Allah.",
    theme: "Celebrates the divine sovereignty over life and death, creation and provision. Challenges the disbelievers to reflect on the perfect structure of creation. Describes those who follow their instinctive guidance versus those who reject clear signs.",
    context: "Revealed in Makkah.",
    notable: "The Prophet ﷺ called it 'al-mani'ah' (the preventer/protector) and said it intercedes for its reader until he is forgiven. Recommended for nightly recitation.",
  },
  68: {
    juz: [29],
    nameOrigin: "Al-Qalam — 'The Pen'. Named for the opening oath by the pen and what it writes.",
    theme: "Among the earliest revelations — defends the Prophet's ﷺ character against accusations of madness, and presents the parable of the garden owners whose arrogance led to its destruction. Warns the disbelievers of a coming punishment.",
    context: "Revealed in the very early Makkan period, as the Quraysh began attacking the Prophet's character.",
    notable: "Verse 68:4 — 'And indeed, you are of a great moral character' — is Allah's direct attestation to the Prophet's ﷺ moral excellence.",
  },
  69: {
    juz: [29],
    nameOrigin: "Al-Haqqa — 'The Inevitable Reality'. Named for one of the names of the Day of Judgment.",
    theme: "Begins with three consecutive names of the Last Day, then describes the fates of those who denied it — 'Ad, Thamud, Pharaoh. Vividly describes the events of that Day and the contrasting fates of the righteous and the sinful.",
    context: "Revealed in Makkah.",
    notable: "Verse 69:44–47 — describing what would have happened if the Prophet ﷺ had fabricated any revelation — is a powerful affirmation of his truthfulness.",
  },
  70: {
    juz: [29],
    nameOrigin: "Al-Ma'arij — 'The Ascending Stairways'. Named for the heavenly stairways described in verse 70:3.",
    theme: "Opens with a question about divine punishment and the reality of the Day of Judgment, described as a day of fifty thousand years. Describes the character of those who are anxious and miserly versus those who pray, give, and guard their trusts.",
    context: "Revealed in Makkah.",
    notable: "Verse 70:19–21 — 'Indeed, mankind was created anxious: when adversity touches him, he is impatient; and when good touches him, he is withholding' — describes the unredeemed human character before faith.",
  },
  71: {
    juz: [29],
    nameOrigin: "Named for the Prophet Nuh (Noah), whose extended mission is its entire subject.",
    theme: "The complete account of Nuh's mission told in his own words: his years of calling, his varied strategies of da'wa — public and private, by day and by night — and his ultimate supplication against those who refused.",
    context: "Revealed in Makkah.",
    notable: "Nuh's supplication (71:26–28) includes a request for the destruction of the disbelievers — granted only after no one on earth would believe. Recorded as one of the most significant prophetic prayers.",
  },
  72: {
    juz: [29],
    nameOrigin: "Al-Jinn — named for the group of jinn who heard the Quran and accepted Islam.",
    theme: "Narrates the account of a group of jinn who heard the Prophet ﷺ recite the Quran, believed, and returned to call their community. Addresses the nature of jinn, their former eavesdropping on heaven, and the complete uniqueness of Allah.",
    context: "Revealed in Makkah, after the Prophet ﷺ was rejected at Ta'if. The encounter with the jinn was a consolation in his moment of deepest rejection.",
    notable: "Verse 72:18 — 'The masjids are for Allah alone, so do not invoke with Allah anyone' — establishes the principle of exclusive worship.",
  },
  73: {
    juz: [29],
    nameOrigin: "Al-Muzzammil — 'The Enwrapped One'. Named for the opening address to the Prophet ﷺ wrapped in his garment.",
    theme: "Commands the Prophet ﷺ to pray by night (tahajjud) as spiritual preparation for his mission. Describes night prayer as the most powerful spiritual practice. Ends with a concession for the community to pray as much as they are able.",
    context: "Among the earliest revelations in Makkah. The Prophet ﷺ and his companions continued the night vigil for a year before the concession at the end of the surah was revealed.",
    notable: "The command to recite the Quran carefully and distinctly (tartil, 73:4) is the Quranic basis for the science of tajweed.",
  },
  74: {
    juz: [29],
    nameOrigin: "Al-Muddaththir — 'The Cloaked One'. Named for the opening address to the Prophet ﷺ wrapped in his cloak.",
    theme: "Commands the Prophet ﷺ to rise and warn, glorify, purify, and be patient. Presents the case of the arrogant who rejected the Quran and the terrifying description of Saqar (one of the levels of Hell).",
    context: "Among the earliest revelations, some scholars say the second surah revealed after Al-Alaq.",
    notable: "Verse 74:38 — 'Every soul is pledged for what it has earned' — is a foundational statement on personal accountability.",
  },
  75: {
    juz: [29],
    nameOrigin: "Al-Qiyama — 'The Resurrection'. Named for the Day of Resurrection.",
    theme: "Confronts the denial of resurrection directly: even if bones are scattered, Allah can reassemble them perfectly. Describes the dying moment's terror, and the contrast between the luminous faces of the believers and the darkened faces of the deniers.",
    context: "Revealed in Makkah.",
    notable: "Verses 75:16–19 — 'Move not your tongue with it to hasten recitation. Indeed, upon Us is its collection and its recitation' — was revealed to assure the Prophet ﷺ that Allah would ensure perfect memorisation.",
  },
  76: {
    juz: [29],
    nameOrigin: "Al-Insan — 'The Human Being'. Also called Ad-Dahr (The Time/Era).",
    theme: "Reminds humanity that there was a time it was nothing, and that it was created with the capacity for choice. Describes the rewards of those who fulfil their vows, feed the poor, and fear the Day — and the beautiful scenes of Paradise awaiting them.",
    context: "Revelation period disputed — some say Makkan, others Medinan. Recommended for recitation at the Fajr prayer on Fridays along with As-Sajdah.",
    notable: "Verses 76:5–22 contain one of the Quran's most detailed and beautiful descriptions of Paradise and its inhabitants.",
  },
  77: {
    juz: [29],
    nameOrigin: "Al-Mursalat — 'Those Sent Forth'. Named for the opening oath by winds or angels sent forth.",
    theme: "Opens with five cosmic oaths and then presents a series of powerful refrains — 'Woe that Day to the deniers!' (repeated ten times) — punctuating descriptions of divine power, the Day of Judgment, and the fate of the righteous and wicked.",
    context: "Revealed in Makkah.",
    notable: "The refrain 'Waylun yawma'idhin lil-mukadhdhibin' (Woe that Day to the deniers!) repeats ten times — the highest repetition of any phrase within a single surah.",
  },
  78: {
    juz: [30],
    nameOrigin: "An-Naba — 'The Great News/Tidings'. Named for 'the great news' of the resurrection (78:2).",
    theme: "Opens with the question: what is this great news that the disbelievers dispute? Answers with cosmic proofs — the creation of earth, mountains, sleep, night and day — leading to the inevitable conclusion of the Day of Judgment and its consequences.",
    context: "Revealed in Makkah. The first surah of the 30th juz.",
    notable: "Verse 78:38 — 'The Day when the Spirit and the angels will stand in rows' — refers to Jibril standing with all angels, describing the majesty of that Day.",
  },
  79: {
    juz: [30],
    nameOrigin: "An-Nazi'at — 'Those who Pull Out'. Named for the opening oath by the angels who pull out souls forcefully.",
    theme: "Opens with a series of oaths by the angels and cosmic events. The story of Musa with Pharaoh is briefly retold. The surah builds to a crescendo with the Day of Judgment and the final moment when earth is transformed.",
    context: "Revealed in Makkah.",
    notable: "Verse 79:40–41 — 'As for one who feared the position of his Lord and restrained the soul from desire, then indeed, Paradise will be his refuge' — is a concise definition of self-discipline in faith.",
  },
  80: {
    juz: [30],
    nameOrigin: "Abasa — 'He Frowned'. Named for the Prophet's ﷺ frowning when a blind man interrupted his conversation.",
    theme: "Gently corrects the Prophet ﷺ for turning away from a sincere seeker while engaging with wealthy disbelievers. Reflects on the ingratitude of humanity despite divine provision, and vividly describes the terror of the Last Day.",
    context: "Revealed in Makkah. The incident involved Abdullah ibn Umm Maktum, a blind companion.",
    notable: "This surah is remarkable in that it respectfully corrects the Prophet ﷺ, affirming that even prophets are held to the highest standards of accessibility and equality.",
  },
  81: {
    juz: [30],
    nameOrigin: "At-Takwir — 'The Folding Up'. Named for the first sign of the Last Day: the sun being folded up.",
    theme: "A dramatic, staccato description of the cosmic upheaval of the Last Day — the sun folded, stars scattered, mountains moved, baby girls asked for what crime they were buried — leading to the moment every soul confronts its deeds.",
    context: "Revealed in Makkah.",
    notable: "Verse 81:1–14 is considered among the most rhetorically powerful descriptions of the Last Day in the Quran.",
  },
  82: {
    juz: [30],
    nameOrigin: "Al-Infitar — 'The Cleaving Asunder'. Named for the splitting of the sky.",
    theme: "Opens with the cosmic signs of the Last Day — sky torn apart, stars scattered, seas burst — and then challenges the human being about ingratitude toward his Creator. Affirms that angels are recording all deeds.",
    context: "Revealed in Makkah.",
    notable: "Verse 82:6 — 'O mankind, what has deceived you concerning your Lord, the Generous' — is a rhetorical challenge to human complacency.",
  },
  83: {
    juz: [30],
    nameOrigin: "Al-Mutaffifin — 'The Defrauders'. Named for those who give short measure in trade.",
    theme: "Vigorously condemns fraud in trade — demanding full measure when receiving but short-changing when giving — as a reflection of denying the Day of Accounting. Contrasts the fate of the wicked (Sijjin) with the righteous (Illiyyun).",
    context: "Revealed in Makkah, though some consider it Medinan as the Prophet ﷺ arrived in Madinah and first saw fraud in the markets.",
    notable: "The Sijjin and Illiyyun — registers of the wicked and righteous deeds — are described here in unique Quranic terms.",
  },
  84: {
    juz: [30],
    nameOrigin: "Al-Inshiqaq — 'The Splitting Open'. Named for the splitting open of the sky.",
    theme: "Describes the sky splitting, the earth stretching out, and the moment every human confronts his record — some receiving it in their right hand with ease, others behind their backs in torment. Calls on humans to progress toward their Lord.",
    context: "Revealed in Makkah.",
    notable: "The Prophet ﷺ prostrated upon this surah (at 84:21), and there is a strong tradition of prostrating at this verse.",
  },
  85: {
    juz: [30],
    nameOrigin: "Al-Buruj — 'The Great Stars/Constellations'. Named for the constellations of the sky.",
    theme: "Commemorates the People of the Trench — believers burned alive for their faith by a tyrannical king. Affirms that divine vengeance will come, the Quran is preserved on a Preserved Tablet, and believers who are persecuted are honoured.",
    context: "Revealed in Makkah, as the early Muslims were enduring severe persecution.",
    notable: "The story of the People of the Trench (Ashab al-Ukhdud) has inspired believers throughout history as a paradigm of standing firm under persecution.",
  },
  86: {
    juz: [30],
    nameOrigin: "At-Tariq — 'The Nightly Star'. Named for the piercing star that appears by night.",
    theme: "Uses the piercing night star as a sign: just as there is a guardian over every soul, so too is Allah watching over all creation. The surah moves to the creation of the human being from fluid, and ends with the certainty of resurrection and the Quran's decisive nature.",
    context: "Revealed in Makkah.",
    notable: "Verse 86:4 — 'There is no soul but that it has over it a protector' — affirms divine oversight over every individual.",
  },
  87: {
    juz: [30],
    nameOrigin: "Al-A'la — 'The Most High'. Named for the opening command to glorify the name of the Most High Lord.",
    theme: "Commands the Prophet ﷺ to glorify Allah and affirms that teaching the Quran is divinely facilitated — 'We will make you recite and you will not forget.' Describes the purification that comes from remembering Allah's name and praying.",
    context: "Revealed in Makkah. One of the first surahs the Prophet ﷺ memorised.",
    notable: "The Prophet ﷺ would recite this surah in the first unit of Friday and Eid prayers. Contains the first mention of zakah as an obligation (87:14).",
  },
  88: {
    juz: [30],
    nameOrigin: "Al-Ghashiya — 'The Overwhelming Event'. Named for the Day of Judgment as the event that overwhelms.",
    theme: "Describes two groups on the Day of Judgment: faces humiliated (the deniers) and faces radiant (the believers). Calls on the human being to reflect on the creation of the camel, sky, mountains, and earth as evidence of divine power.",
    context: "Revealed in Makkah. The Prophet ﷺ would recite this surah along with Al-A'la on Fridays and Eid.",
    notable: "Verses 88:17–20 use four simple natural wonders — camel, sky, mountains, earth — as accessible arguments for reflection on divine power.",
  },
  89: {
    juz: [30],
    nameOrigin: "Al-Fajr — 'The Dawn'. Named for the opening oath by the dawn.",
    theme: "Opens with cosmic oaths, then recounts the fates of 'Ad, Thamud, and Pharaoh — destroyed for their tyranny and corruption. Reflects on how humans are tested by wealth and poverty. Ends with the sublime invitation to the peaceful soul to enter Paradise.",
    context: "Revealed in Makkah.",
    notable: "The closing address — 'O peaceful soul, return to your Lord well-pleased and pleasing. Enter among My servants. Enter My Paradise' (89:27–30) — is among the most comforting passages in the Quran.",
  },
  90: {
    juz: [30],
    nameOrigin: "Al-Balad — 'The City'. Named for the oath by the city of Makkah.",
    theme: "Reflects on the trials inherent in human life and the two paths — the path of effort and virtue versus the path of ease and selfishness. The 'steep path' includes freeing slaves, feeding the orphaned, and joining the community of faith.",
    context: "Revealed in Makkah.",
    notable: "The 'aqabah — the steep mountain pass — as a metaphor for the difficult path of righteousness (90:11) is one of the Quran's most vivid moral images.",
  },
  91: {
    juz: [30],
    nameOrigin: "Ash-Shams — 'The Sun'. Named for the opening oath by the sun.",
    theme: "Seven magnificent oaths of nature lead to the statement that success belongs to those who purify their souls and failure to those who corrupt them. The story of the she-camel of Thamud illustrates the consequences of corrupt self-destructiveness.",
    context: "Revealed in Makkah.",
    notable: "The seven consecutive oaths (sun, moon, day, night, sky, earth, soul) make this one of the most rhetorically striking openings in the Quran.",
  },
  92: {
    juz: [30],
    nameOrigin: "Al-Layl — 'The Night'. Named for the opening oath by the night when it covers.",
    theme: "Contrasts two human paths: the one who gives, fears Allah, and confirms goodness — and the one who is miserly, self-sufficient, and denies goodness. Promises ease to the former and difficulty to the latter. Uses the example of the noble spender.",
    context: "Revealed in Makkah. Believed to refer partly to Abu Bakr's generosity in freeing enslaved believers.",
    notable: "Verse 92:21 — 'And they will not give except seeking the face of their Lord Most High' — describes the purest form of generosity: giving for Allah alone.",
  },
  93: {
    juz: [30],
    nameOrigin: "Ad-Duha — 'The Morning Brightness'. Named for the radiance of the morning.",
    theme: "A divine reassurance to the Prophet ﷺ after a period of silence in revelation, during which he feared he had been abandoned. Allah reminds him of His care throughout his life and commands him to gratitude, generosity, and proclamation.",
    context: "Revealed in Makkah, after an extended pause in revelation that deeply distressed the Prophet ﷺ.",
    notable: "This surah was a direct comfort to the Prophet ﷺ. It is recommended to recite as a daily affirmation of divine care.",
  },
  94: {
    juz: [30],
    nameOrigin: "Ash-Sharh / Al-Inshirah — 'The Relief/Opening'. Named for the divine opening of the Prophet's chest.",
    theme: "A continuation of the reassurance in Ad-Duha. Reminds the Prophet ﷺ of the spiritual expansion, the lightening of his burden, and the elevation of his mention worldwide. Promises that after difficulty comes ease — twice.",
    context: "Revealed in Makkah.",
    notable: "Verse 94:5–6 — 'Indeed, with difficulty comes ease; indeed, with difficulty comes ease' — repeats twice, which the Prophet ﷺ explained means one difficulty cannot overcome two eases.",
  },
  95: {
    juz: [30],
    nameOrigin: "At-Tin — 'The Fig'. Named for the opening oath by the fig and the olive.",
    theme: "Swears by four sacred things — the fig (associated with Sham), the olive (Jerusalem), Mount Sinai, and this secure city (Makkah) — to declare that the human being was created in the finest form but can be reduced to the lowest if ungrateful.",
    context: "Revealed in Makkah.",
    notable: "The phrase 'ahsan taqwim' — 'the finest form or constitution' (95:4) — is the Quran's definitive statement on the dignity of the human being.",
  },
  96: {
    juz: [30],
    nameOrigin: "Al-Alaq — 'The Clinging Substance / Blood Clot'. Named for the second stage of human embryonic development.",
    theme: "The first revelation ever received by the Prophet ﷺ — the command to read in the name of the Lord who created. Establishes that knowledge comes from Allah and that all learning must be anchored in divine consciousness.",
    context: "The first five verses were revealed at the Cave of Hira, the first revelation to any prophet in this era. The remaining verses were revealed later.",
    notable: "The first words of the Quran revealed to humanity: 'Iqra bismi rabbika alladhi khalaq' — 'Read in the name of your Lord who created.'",
  },
  97: {
    juz: [30],
    nameOrigin: "Al-Qadr — 'The Power/Majesty'. Named for Laylat al-Qadr, the Night of Power.",
    theme: "Celebrates the Laylat al-Qadr — the night better than a thousand months — when the Quran was first revealed and angels descend with divine decrees. The entire night is described as peace until the break of dawn.",
    context: "Revealed in Makkah. The precise date of Laylat al-Qadr is unknown but sought in the last ten nights of Ramadan, particularly the odd nights.",
    notable: "One night of worship in Laylat al-Qadr is said to be better than a thousand months (over 83 years) of worship.",
  },
  98: {
    juz: [30],
    nameOrigin: "Al-Bayyina — 'The Clear Proof'. Named for the clear proof — the Prophet ﷺ and the Quran — sent to humanity.",
    theme: "Addresses why the People of the Book divided despite having a clear proof. Affirms that the religion of pure monotheism and righteous deeds is the straight path, and distinguishes the best and worst of creation on the Last Day.",
    context: "Revelation period debated — some say Makkan, others Medinan.",
    notable: "Verse 98:5 — 'And they were not commanded except to worship Allah, sincere to Him in religion, inclining to truth' — is a definitive summary of the purpose of all divine religion.",
  },
  99: {
    juz: [30],
    nameOrigin: "Az-Zalzala — 'The Earthquake'. Named for the great earthquake of the Last Day.",
    theme: "Describes the earth shaking violently and disclosing all it contains, while every human being witnesses the totality of their deeds — an atom's weight of good and an atom's weight of evil.",
    context: "Revealed in Madinah according to the majority of scholars.",
    notable: "Verse 99:7–8 — 'Whoever does an atom's weight of good will see it; and whoever does an atom's weight of evil will see it' — is one of the most precise statements on the comprehensive nature of divine accounting.",
  },
  100: {
    juz: [30],
    nameOrigin: "Al-Adiyat — 'The Charging Mares'. Named for the warhorses charging into battle.",
    theme: "Opens with the oath of charging warhorses to confront human ingratitude toward their Lord. The surah uses the loyalty of a horse to its rider as a contrast to the disloyalty of humans toward Allah. Ends with the Day when hearts will be exposed.",
    context: "Revealed in Makkah.",
    notable: "The oath by the warhorses is one of the Quran's most vivid and energetic openings, conveying both physical dynamism and moral urgency.",
  },
  101: {
    juz: [30],
    nameOrigin: "Al-Qari'a — 'The Striking Calamity'. Named for the Day of Judgment as the event that strikes.",
    theme: "Describes the Day of Judgment as a striking calamity — people like scattered moths, mountains like fluffed wool — leading to the weighing of deeds: heavy scales means a pleasant life, light scales means a bottomless pit.",
    context: "Revealed in Makkah.",
    notable: "The 'Hawiya' — the bottomless pit described as a blazing fire (101:9–11) — is one of the Quran's unique names for a portion of Hell.",
  },
  102: {
    juz: [30],
    nameOrigin: "At-Takathur — 'The Rivalry in World Increase'. Named for the human obsession with accumulating more.",
    theme: "Sharply rebukes the human obsession with accumulating wealth and status until death comes. States that even then the distraction continues — until the reality of the grave and the Day of Judgment arrives.",
    context: "Revelation period debated — most say Makkan.",
    notable: "The Prophet ﷺ said: 'The son of Adam says: My wealth, my wealth — but your wealth is only what you ate and consumed, what you wore and wore out, or what you gave in charity and sent forward' (Muslim).",
  },
  103: {
    juz: [30],
    nameOrigin: "Al-Asr — 'The Time/The Epoch'. Named for the oath by time.",
    theme: "By the oath of time: every human being is in loss — except those who believe, do righteous deeds, counsel each other to truth, and counsel each other to patience. A complete theory of success in three verses.",
    context: "Revealed in Makkah.",
    notable: "Imam al-Shafi'i said: 'If people reflected only on this surah, it would be sufficient for them.' The entire Quran's message of faith, deed, truth, and patience is compressed into three verses.",
  },
  104: {
    juz: [30],
    nameOrigin: "Al-Humazah — 'The Backbiter/Slanderer'. Named for those who habitually slander.",
    theme: "A sharp condemnation of those who habitually slander and mock others, accumulate wealth and count it compulsively, thinking it will make them immortal. Describes the fire that consumes hearts.",
    context: "Revealed in Makkah. Believed to refer to Akhnas ibn Shariq and similar figures who harassed the Prophet ﷺ and his companions.",
    notable: "The 'fire that reaches the hearts' (104:7) — al-Hutama — is interpreted as a fire of a unique, all-consuming nature.",
  },
  105: {
    juz: [30],
    nameOrigin: "Al-Fil — 'The Elephant'. Named for the army of Abraha who came with elephants to destroy the Ka'ba.",
    theme: "Recalls the miraculous destruction of Abraha's army — who came with elephants to destroy the Ka'ba — by birds dropping stones of baked clay. A reminder that the House of Allah is under divine protection.",
    context: "Revealed in Makkah. The Year of the Elephant (570 CE) was the year of the Prophet's ﷺ birth, making this event personal sacred history.",
    notable: "The miraculous destruction of the Army of the Elephant is historically documented and was a living memory for the people of Makkah when this surah was revealed.",
  },
  106: {
    juz: [30],
    nameOrigin: "Quraysh — named for the tribe of Quraysh, the guardians of the Ka'ba.",
    theme: "Reminds the Quraysh of the two divine blessings that made them prosperous — the winter trade journey to Yemen and summer journey to Syria — and commands them to worship the Lord of this House who provided them security and food.",
    context: "Revealed in Makkah. This surah and Al-Fil together are sometimes treated as a single unit in traditional recitation.",
    notable: "The Quraysh's privileged status as guardians of the Ka'ba depended entirely on divine protection — a point designed to prompt their gratitude and worship.",
  },
  107: {
    juz: [30],
    nameOrigin: "Al-Ma'un — 'The Small Kindnesses'. Named for the small acts of neighbourly assistance the surah condemns neglecting.",
    theme: "Identifies the one who denies the Day of Judgment by their behaviour: they push away the orphan and do not encourage feeding the needy. Among the believers, it targets those who pray only to be seen and refuse to lend even small utilities.",
    context: "Revealed in Makkah. Contains one of the sharpest social justice critiques in the Quran.",
    notable: "Verse 107:4–7 warns against those who pray but are heedless of its purpose — their prayer becomes show rather than sincere devotion.",
  },
  108: {
    juz: [30],
    nameOrigin: "Al-Kawthar — 'The Abundant Good/The River of Paradise'. Named for the divine gift of al-Kawthar promised to the Prophet ﷺ.",
    theme: "The shortest surah: a divine gift of abundance, a command to pray and sacrifice for Allah, and a declaration that the Prophet's ﷺ enemies — not he — will be cut off from all good.",
    context: "Revealed in Makkah as a response to those who mocked the Prophet ﷺ for having no surviving sons.",
    notable: "At three verses, it is the shortest surah. Al-Kawthar is described in hadith as a river in Paradise whiter than milk and sweeter than honey.",
  },
  109: {
    juz: [30],
    nameOrigin: "Al-Kafirun — 'The Disbelievers'. Named for its direct address to the disbelievers.",
    theme: "A clear, uncompromising declaration of the total incompatibility between monotheism and polytheism. States that the Prophet ﷺ will never worship what the disbelievers worship, and they will not worship what he worships — the most decisive statement of mutual non-interference.",
    context: "Revealed in Makkah when the Quraysh proposed mutual religious accommodation — worshipping each other's gods alternately.",
    notable: "Called the 'Surah of Bara'a' (Disavowal). The Prophet ﷺ recommended reciting this surah before sleeping as a declaration of faith.",
  },
  110: {
    juz: [30],
    nameOrigin: "An-Nasr — 'The Divine Help/Victory'. Named for the divine help promised in the opening verse.",
    theme: "Prophesies the conquest of Makkah and the mass entry of people into Islam. Commands the Prophet ﷺ to glorify his Lord, seek forgiveness, and recognise that this victory signals the nearing of his departure from this world.",
    context: "Among the last surahs revealed, shortly before the Farewell Pilgrimage (10 AH). When Abu Bakr heard it, he wept — understanding that it announced the Prophet's ﷺ imminent passing.",
    notable: "When 'Umar ibn al-Khattab gathered the senior companions after the Prophet's death, Ibn Abbas, the youngest, interpreted this surah as the announcement of the Prophet's death — and 'Umar confirmed he had understood correctly.",
  },
  111: {
    juz: [30],
    nameOrigin: "Al-Masad — 'The Palm Fibre'. Named for the rope of palm fibre around the neck of Abu Lahab's wife.",
    theme: "A direct condemnation of Abu Lahab — the Prophet's ﷺ uncle and one of his fiercest enemies — and his wife, declaring that neither his wealth nor his deeds will save him from the fire. His wife will carry wood to fuel that fire.",
    context: "Revealed in Makkah. Abu Lahab refused to believe even after his nephew's prophethood was publicly declared.",
    notable: "The only surah where a specific named individual is condemned. Abu Lahab was still alive when this was revealed, yet never accepted Islam — fulfilling the prophecy.",
  },
  112: {
    juz: [30],
    nameOrigin: "Al-Ikhlas — 'Sincerity/Purity of Faith'. Named for the purity of monotheism it declares.",
    theme: "The most concentrated declaration of divine oneness in the Quran: Allah is One, the Eternal Refuge, He neither begets nor was begotten, and there is none like Him. Refutes both polytheism and the Christian doctrine of divine sonship.",
    context: "Revealed in Makkah, reportedly in response to questions from the Quraysh or People of the Book about the nature of Allah.",
    notable: "Equivalent to one-third of the Quran in reward, according to authentic hadith. The Prophet ﷺ loved this surah deeply and said whoever recites it ten times, Allah builds him a house in Paradise.",
  },
  113: {
    juz: [30],
    nameOrigin: "Al-Falaq — 'The Daybreak'. Named for the opening: 'Say, I seek refuge in the Lord of the daybreak.'",
    theme: "A prayer of seeking refuge with Allah from four specific evils: the harm of all creation, the harm of darkness when it settles, the harm of those who blow on knots (magicians), and the harm of an envier when he envies.",
    context: "Revealed in Makkah, though some say Madinah. Part of the Mu'awwidhatain — the two surahs of taking refuge.",
    notable: "The Prophet ﷺ recited these two surahs (Al-Falaq and An-Nas) after every prayer and before sleeping. Called the Mu'awwidhatain (the two protectors).",
  },
  114: {
    juz: [30],
    nameOrigin: "An-Nas — 'Mankind'. Named for the opening: 'Say, I seek refuge in the Lord of mankind.'",
    theme: "Seeks refuge from the whispering tempter — the jinn or human — who whispers into the hearts of people and withdraws when Allah is remembered. The final surah of the Quran.",
    context: "Revealed in Makkah, though some say Madinah. The last surah in the Quranic arrangement.",
    notable: "The Quran ends with the command to seek refuge from the whisperer — acknowledging that even after receiving divine guidance, human hearts remain in need of divine protection.",
  },
};
