/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MemorizeRouteImport } from './routes/memorize'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurahSurahIdRouteImport } from './routes/surah.$surahId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorizeRoute = MemorizeRouteImport.update({
  id: '/memorize',
  path: '/memorize',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurahSurahIdRoute = SurahSurahIdRouteImport.update({
  id: '/surah/$surahId',
  path: '/surah/$surahId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/memorize': typeof MemorizeRoute
  '/search': typeof SearchRoute
  '/surah/$surahId': typeof SurahSurahIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/memorize': typeof MemorizeRoute
  '/search': typeof SearchRoute
  '/surah/$surahId': typeof SurahSurahIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/memorize': typeof MemorizeRoute
  '/search': typeof SearchRoute
  '/surah/$surahId': typeof SurahSurahIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bookmarks' | '/memorize' | '/search' | '/surah/$surahId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bookmarks' | '/memorize' | '/search' | '/surah/$surahId'
  id:
    | '__root__'
    | '/'
    | '/bookmarks'
    | '/memorize'
    | '/search'
    | '/surah/$surahId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarksRoute: typeof BookmarksRoute
  MemorizeRoute: typeof MemorizeRoute
  SearchRoute: typeof SearchRoute
  SurahSurahIdRoute: typeof SurahSurahIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorize': {
      id: '/memorize'
      path: '/memorize'
      fullPath: '/memorize'
      preLoaderRoute: typeof MemorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surah/$surahId': {
      id: '/surah/$surahId'
      path: '/surah/$surahId'
      fullPath: '/surah/$surahId'
      preLoaderRoute: typeof SurahSurahIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarksRoute: BookmarksRoute,
  MemorizeRoute: MemorizeRoute,
  SearchRoute: SearchRoute,
  SurahSurahIdRoute: SurahSurahIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
